import { defineConfig } from "tsdown"

export default defineConfig([
  {
    banner: { js: "#!/usr/bin/env node" },
    dts: true,
    entry: { "monorepo-hash": "./src/entry-esm.ts" },
    exports: true,
    format: ["esm"],
    minify: true,
    nodeProtocol: true,
    noExternal: [
      "fast-glob",
      "find-up",
      "ignore",
      "js-yaml",
    ],
    platform: "node",
    shims: true,
    target: [ "esnext", "node20" ],
    unused: true,
  },
  {
    cjsDefault: true,
    dts: false,
    entry: { "monorepo-hash": "./src/entry-cjs.ts" },
    exports: false,
    format: ["cjs"],
    minify: true,
    nodeProtocol: true,
    noExternal: [
      "fast-glob",
      "find-up",
      "ignore",
      "js-yaml",
    ],
    platform: "node",
    shims: true,
    target: [ "esnext", "node20" ],
  },
  {
    banner: { js: "#!/usr/bin/env node" },
    dts: false,
    entry: { "monorepo-hash-bun": "./src/cli-launcher.ts" },
    exports: false,
    format: ["esm"],
    minify: true,
    nodeProtocol: true,
    platform: "node",
    shims: true,
    target: [ "esnext", "node20" ],
  },
])
