import { pathToFileURL } from "node:url"

import {
  PACKAGE_MANAGERS,
  type PackageManager,
  type PnpmWorkspaceConfig,
  type PackageManifest,
  type PackageInfo,
  log,
  exists,
  zeroPad,
  safeExit,
  mapLimit,
  getWorkspaceFileList,
  isPackageManager,
  detectPNPM,
  detectDeno,
  detectPkgJson,
  autoDetect,
  detectSpecified,
  writeDebugFile,
  loadDebugFile,
  writeRootDebugFile,
  loadRootDebugFile,
  generateDebug,
  computePerFileHashes,
  computeOwnHashFromPerFile,
  computeFinalHash,
  writeRootHashFile,
  loadRootHashFile,
  generateHashes,
  compareHashes,
  hash,
  runCli,
} from "./monorepo-hash"

// Auto-run only when executed as the main entry point (not when imported)
if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  await runCli()
}

export {
  PACKAGE_MANAGERS,
  type PackageManager,
  type PnpmWorkspaceConfig,
  type PackageManifest,
  type PackageInfo,
  log,
  exists,
  zeroPad,
  safeExit,
  mapLimit,
  getWorkspaceFileList,
  isPackageManager,
  detectPNPM,
  detectDeno,
  detectPkgJson,
  autoDetect,
  detectSpecified,
  writeDebugFile,
  loadDebugFile,
  writeRootDebugFile,
  loadRootDebugFile,
  generateDebug,
  computePerFileHashes,
  computeOwnHashFromPerFile,
  computeFinalHash,
  writeRootHashFile,
  loadRootHashFile,
  generateHashes,
  compareHashes,
  hash,
  runCli,
}

export default runCli
