name: Benchmarks the CLI tool

on:
  pull_request:
    types: [labeled]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      benchs:
        description: 'Run specific benchmarks only (comma-separated values: small,medium,large,wide), leave empty to run all'
        required: false
        default: ''
      ref:
        description: 'Git reference (branch, tag, or SHA)'
        required: false
        default: 'master'

jobs:
  benchmark:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.label.name == 'benchmark-this') }}
    name: "Benchmark CLI tool"
    runs-on: ubuntu-24.04
    timeout-minutes: 45

    steps:
      - name: Get the Git reference
        id: get_ref
        run: |
          if [[ "${{ github.event.inputs.ref }}" != "" ]]; then
            echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          else
            ref="${{ github.ref }}"
            echo "ref=${ref##*/}" >> $GITHUB_OUTPUT
          fi

      - name: "Checkout code at ${{ steps.get_ref.outputs.ref }}"
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.get_ref.outputs.ref }}

      - name: "Install pnpm"
        uses: pnpm/action-setup@v5

      - name: "Bump Node.js to v25"
        uses: actions/setup-node@v6
        with:
          check-latest: true
          cache: "pnpm"
          node-version: 25

      - name: "Install Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Install dependencies"
        run: |
          pnpm i --frozen-lockfile
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine_1.20.0_amd64.deb
          sudo dpkg -i hyperfine_1.20.0_amd64.deb
          rm hyperfine_1.20.0_amd64.deb
          sudo add-apt-repository ppa:zhangsongcui3371/fastfetch -y
          sudo apt-get update
          sudo apt-get install fastfetch lshw -y

      - name: "Get the system specs"
        run: |
          echo "System Specs :"
          echo "CPU : $(lscpu | grep 'Model name')"
          echo "RAM : $(free -h | grep 'Mem' | awk '{print $2}')"
          echo "Disk : $(df -h | grep '/$' | awk '{print $2}')"
          echo "OS : $(lsb_release -d | awk -F'\t' '{print $2}')"
          echo "Fastfetch :"
          fastfetch -c all.jsonc
          echo "lshw :"
          sudo lshw -short
      
      - name: "Get the benchmarks to run"
        id: get_benchs
        run: |
          if [[ "${{ github.event.inputs.benchs }}" != "" ]]; then
            echo "benchs=${{ github.event.inputs.benchs }}" >> $GITHUB_OUTPUT
          else
            echo "benchs=small,medium,large,wide" >> $GITHUB_OUTPUT
          fi
          if grep -q '"build:bun"' package.json; then
            echo "build_bun=true" >> $GITHUB_OUTPUT
          else
            echo "build_bun=false" >> $GITHUB_OUTPUT
          fi
          if grep -q '"build:node"' package.json; then
            echo "build_node=true" >> $GITHUB_OUTPUT
          else
            echo "build_node=false" >> $GITHUB_OUTPUT
          fi
          if grep -q '"build:rust"' package.json; then
            echo "build_rust=true" >> $GITHUB_OUTPUT
          else
            echo "build_rust=false" >> $GITHUB_OUTPUT
          fi

      - name: "Prepare the benchmarks"
        id: prepare_benchs
        run: |
          if [[ "${{ steps.get_benchs.outputs.build_node }}" == "true" ]]; then
            pnpm build:node
          else
            pnpm build
          fi
          if [[ "${{ steps.get_benchs.outputs.build_rust }}" == "true" ]]; then
            pnpm build:rust:linux-x64
            chmod +x rust-build/monorepo-hash-linux-x64
            mkdir -p tests/benchmarks/rust
          fi
          if [[ "${{ steps.get_benchs.outputs.build_bun }}" == "true" ]]; then
            pnpm build:bun:linux-x64
            chmod +x bun-build/monorepo-hash-linux-x64
            mkdir -p tests/benchmarks/bun
          fi
          if [[ ! -f tests/demo/wide-monorepo.7z ]]; then
            wget https://raw.githubusercontent.com/EDM115/monorepo-hash/refs/heads/master/tests/demo/wide-monorepo.7z -O tests/demo/wide-monorepo.7z
          fi
          if [[ -f dist/monorepo-hash.js ]]; then
            js_name=monorepo-hash.js
          else
            js_name=monorepo-hash.mjs
          fi
          echo "js_name=$js_name" >> $GITHUB_OUTPUT
          if grep -q '(-pm)' src/monorepo-hash.ts; then
            pm_arg='-pm=pnpm'
          else
            pm_arg=''
          fi
          echo "pm_arg=$pm_arg" >> $GITHUB_OUTPUT
          mkdir -p tests/benchmarks/node
          IFS=',' read -ra BENCHES <<< "${{ steps.get_benchs.outputs.benchs }}"
          for b in "${BENCHES[@]}"; do
            b="$(echo "$b" | xargs)"
            echo "Preparing $b..."

            7z x "tests/demo/${b}-monorepo.7z" -o./tests/demo
            cp dist/$js_name "tests/demo/${b}-monorepo/$js_name"
            if [[ "${{ steps.get_benchs.outputs.build_rust }}" == "true" ]]; then
              cp rust-build/monorepo-hash-linux-x64 "tests/demo/${b}-monorepo/monorepo-hash-rust"
            fi
            if [[ "${{ steps.get_benchs.outputs.build_bun }}" == "true" ]]; then
              cp bun-build/monorepo-hash-linux-x64 "tests/demo/${b}-monorepo/monorepo-hash"
            fi
          done

      - name: "Benchmark : small monorepo, rust, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'small') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/small-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/small-monorepo-cold.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : small monorepo, rust, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'small') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/small-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/small-monorepo-warm.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : medium monorepo, rust, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'medium') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/medium-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/medium-monorepo-cold.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : medium monorepo, rust, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'medium') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/medium-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/medium-monorepo-warm.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : large monorepo, rust, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'large') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/large-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/large-monorepo-cold.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : large monorepo, rust, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'large') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/large-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/large-monorepo-warm.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : wide monorepo, rust, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'wide') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/wide-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/wide-monorepo-cold.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : wide monorepo, rust, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'wide') && steps.get_benchs.outputs.build_rust == 'true'
        run: |
          cd tests/demo/wide-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/rust/wide-monorepo-warm.md \
            "./monorepo-hash-rust --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : small monorepo, bun (cold)"
        if: contains(steps.get_benchs.outputs.benchs, 'small') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/small-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/small-monorepo-cold.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : small monorepo, bun (warm)"
        if: contains(steps.get_benchs.outputs.benchs, 'small') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/small-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/small-monorepo-warm.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : medium monorepo, bun, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'medium') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/medium-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/medium-monorepo-cold.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : medium monorepo, bun, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'medium') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/medium-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/medium-monorepo-warm.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : large monorepo, bun, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'large') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/large-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/large-monorepo-cold.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : large monorepo, bun, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'large') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/large-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/large-monorepo-warm.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : wide monorepo, bun, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'wide') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/wide-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/wide-monorepo-cold.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : wide monorepo, bun, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'wide') && steps.get_benchs.outputs.build_bun == 'true'
        run: |
          cd tests/demo/wide-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/bun/wide-monorepo-warm.md \
            "./monorepo-hash --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : small monorepo, node, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'small')
        run: |
          cd tests/demo/small-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/small-monorepo-cold.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : small monorepo, node, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'small')
        run: |
          cd tests/demo/small-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/small-monorepo-warm.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : medium monorepo, node, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'medium')
        run: |
          cd tests/demo/medium-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/medium-monorepo-cold.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : medium monorepo, node, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'medium')
        run: |
          cd tests/demo/medium-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/medium-monorepo-warm.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : large monorepo, node, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'large')
        run: |
          cd tests/demo/large-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/large-monorepo-cold.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : large monorepo, node, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'large')
        run: |
          cd tests/demo/large-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/large-monorepo-warm.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : wide monorepo, node, cold"
        if: contains(steps.get_benchs.outputs.benchs, 'wide')
        run: |
          cd tests/demo/wide-monorepo
          hyperfine \
            --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/wide-monorepo-cold.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Benchmark : wide monorepo, node, warm"
        if: contains(steps.get_benchs.outputs.benchs, 'wide')
        run: |
          cd tests/demo/wide-monorepo
          hyperfine \
            --warmup 2 \
            --runs 10 \
            --export-markdown ../../benchmarks/node/wide-monorepo-warm.md \
            "node ${{ steps.prepare_benchs.outputs.js_name }} --generate ${{ steps.prepare_benchs.outputs.pm_arg }} -s"

      - name: "Upload benchmarks results"
        uses: actions/upload-artifact@v7
        with:
          name: benchmarks-results-${{ steps.get_ref.outputs.ref }}
          path: tests/benchmarks/**/*.md
