name: Builds the binaries on all targets and all platforms

on:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-slim
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      actions: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6


      - name: "Fire up all the builds"
        run: |
          gh workflow run build-bun.yml
