name: Builds the binaries on all targets and all platforms

on:
  workflow_dispatch:

jobs:
  build-go:
    uses: ./.github/workflows/build-go.yml

  build-rust:
    uses: ./.github/workflows/build-rust.yml
