name: Run the tests suite

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  pr-check:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.label.name == 'test-this') }}
    name: "Tests check"
    runs-on: ubuntu-slim
    timeout-minutes: 20

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install PNPM"
        uses: pnpm/action-setup@v5

      - name: "Bump Node to v25"
        uses: actions/setup-node@v6
        with:
          check-latest: true
          cache: "pnpm"
          node-version: 25

      - name: "Install Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install Go"
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: "./src/go/go.sum"
          check-latest: true
          go-version: "stable"

      - name: "Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          rust-src-dir: ./src/rust
          toolchain: stable

      - name: "Install dependencies"
        run: |
          pnpm i --frozen-lockfile
          cd src/go && go mod download
          cd ../rust && cargo fetch --locked

      - name: "Lint check"
        run: pnpm lint

      - name: "Types check"
        run: pnpm typecheck

      - name: "Build the project"
        run: |
          pnpm build:node
          pnpm cli:build-bin -r bun -p linux-x64
          pnpm cli:build-bin -r go -p linux-x64
          pnpm cli:build-bin -r rust -p linux-x64
          pnpm cli:chmod

      - name: "Run the Node tests"
        run: pnpm vitest --project node

      - name: "Run the Bun tests"
        run: pnpm vitest --project bun

      - name: "Run the Go tests"
        run: pnpm vitest --project go

      - name: "Run the Rust tests"
        run: pnpm vitest --project rust
