name: Run the tests suite

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  pr-check:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.label.name == 'test-this') }}
    name: "Tests check"
    runs-on: ubuntu-slim
    timeout-minutes: 20

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4

      - name: "Bump Node.js to v25"
        uses: actions/setup-node@v6
        with:
          check-latest: true
          cache: "pnpm"
          node-version: 25

      - name: "Install Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        run: pnpm i --frozen-lockfile

      - name: "Lint check"
        run: pnpm lint
      
      - name: "Types check"
        run: pnpm typecheck

      - name: "Build the project"
        run: pnpm build:node && pnpm build:bun:linux-x64 && pnpm build:bun:linux-arm64 && pnpm build:bun:windows-x64:ci && pnpm build:bun:windows-arm64:ci && pnpm build:bun:darwin-x64 && pnpm build:bun:darwin-arm64 && pnpm build:bun:linux-x64-musl && pnpm build:bun:linux-arm64-musl && pnpm build:bun:chmod

      - name: "Run the node tests"
        run: pnpm vitest --project node

      - name: "Run the bun tests"
        run: pnpm test:bun:prepare && pnpm vitest --project bun
